// agentFallBack/auto_page_object_creator.mjs
// Auto Page Object Creator for Generic Mode
import fs from "node:fs";
import path from "node:path";

const agentDir = process.cwd();
const repoRoot = path.resolve(agentDir, "..");

function createPageObjectFolder() {
    const pageObjectsDir = path.join(repoRoot, "page-objects");
    
    if (!fs.existsSync(pageObjectsDir)) {
        console.log("📁 Creating page-objects folder...");
        fs.mkdirSync(pageObjectsDir, { recursive: true });
        
        // Create index.ts
        const indexContent = `// Page Objects Index
// Auto-generated by AI Agent

export * from './BasePage';
`;
        fs.writeFileSync(path.join(pageObjectsDir, "index.ts"), indexContent);
        
        // Create BasePage.ts
        const basePageContent = `import { Page, Locator } from '@playwright/test';

export class BasePage {
    constructor(public page: Page) {}

    // Common utility methods
    async waitForPageLoad(): Promise<void> {
        await this.page.waitForLoadState('networkidle');
    }

    async isVisible(locator: Locator): Promise<boolean> {
        try {
            return await locator.isVisible({ timeout: 5000 });
        } catch {
            return false;
        }
    }

    async clickElement(locator: Locator): Promise<void> {
        await locator.waitFor({ state: 'visible' });
        await locator.click();
    }

    async fillInput(locator: Locator, value: string): Promise<void> {
        await locator.waitFor({ state: 'visible' });
        await locator.fill(value);
    }

    async getElementText(locator: Locator): Promise<string> {
        await locator.waitFor({ state: 'visible' });
        return await locator.textContent() || '';
    }
}
`;
        fs.writeFileSync(path.join(pageObjectsDir, "BasePage.ts"), basePageContent);
        
        console.log("✅ Created page-objects folder with BasePage");
        return true;
    }
    
    return false;
}

function createUtilsFolder() {
    const utilsDir = path.join(repoRoot, "utils");
    
    if (!fs.existsSync(utilsDir)) {
        console.log("📁 Creating utils folder...");
        fs.mkdirSync(utilsDir, { recursive: true });
        
        // Create testHelpers.ts
        const testHelpersContent = `// Test Helpers
// Auto-generated by AI Agent

import { Page, expect } from '@playwright/test';

export class TestHelpers {
    static async verifyLinks(page: Page, maxLinks: number = 10): Promise<void> {
        const links = await page.locator('a[href]').all();
        console.log(\`Found \${links.length} links to verify\`);
        
        for (let i = 0; i < Math.min(links.length, maxLinks); i++) {
            const link = links[i];
            const href = await link.getAttribute('href');
            const isVisible = await link.isVisible();
            
            if (isVisible && href && !href.startsWith('mailto:') && !href.startsWith('tel:')) {
                console.log(\`Verifying link: \${href}\`);
                expect(href).toBeTruthy();
                expect(href).toMatch(/^https?:\\/\\//);
            }
        }
    }

    static async verifyImages(page: Page, maxImages: number = 10): Promise<void> {
        const images = await page.locator('img').all();
        
        for (const img of images.slice(0, maxImages)) {
            const isVisible = await img.isVisible();
            if (isVisible) {
                const src = await img.getAttribute('src');
                if (src) {
                    expect(src).toBeTruthy();
                    const naturalWidth = await img.evaluate(img => img.naturalWidth);
                    expect(naturalWidth).toBeGreaterThan(0);
                }
            }
        }
    }

    static async verifyPageHealth(page: Page): Promise<void> {
        await expect(page.locator('body')).toBeVisible();
        
        const pageTitle = await page.title();
        expect(pageTitle.length).toBeGreaterThan(0);
        console.log(\`Page title: \${pageTitle}\`);
        
        const hasHeader = await page.locator('header, .header, nav').isVisible().catch(() => false);
        const hasContent = await page.locator('main, .main, .content').isVisible().catch(() => false);
        
        console.log(\`Header visible: \${hasHeader}, Content visible: \${hasContent}\`);
    }
}
`;
        fs.writeFileSync(path.join(utilsDir, "testHelpers.ts"), testHelpersContent);
        
        // Create index.ts for utils
        const utilsIndexContent = `export * from './testHelpers';
`;
        fs.writeFileSync(path.join(utilsDir, "index.ts"), utilsIndexContent);
        
        console.log("✅ Created utils folder with TestHelpers");
        return true;
    }
    
    return false;
}

function createLandingPagePO() {
    const pageObjectsDir = path.join(repoRoot, "page-objects");
    
    const landingPageContent = `import { Page, Locator } from '@playwright/test';
import { BasePage } from './BasePage';

export class LandingPage extends BasePage {
    // Selectors
    private readonly tryButtonSelector: Locator;
    private readonly linksSelector: Locator;
    private readonly imagesSelector: Locator;
    private readonly headerSelector: Locator;

    constructor(page: Page) {
        super(page);
        this.tryButtonSelector = page.locator('button:has-text("Try Calm for Free")').first();
        this.linksSelector = page.locator('a[href]');
        this.imagesSelector = page.locator('img');
        this.headerSelector = page.locator('header, .header, nav');
    }

    // Page Actions with enhanced logging
    async navigateTo(url: string): Promise<void> {
        console.log(\`🌐 Starting navigation to: \${url}\`);
        console.log('⏰ Waiting for page load...');
        await this.page.goto(url);
        await this.waitForPageLoad();
        console.log('✅ Navigation completed successfully');
        console.log(\`📍 Current URL: \${this.page.url()}\`);
    }

    async clickTryButton(): Promise<void> {
        console.log('🎯 Attempting to click "Try Calm for Free" button');
        await this.verifyTryButtonVisible();
        console.log('🖱️ Clicking button...');
        await this.clickElement(this.tryButtonSelector);
        await this.waitForPageLoad();
        console.log('✅ Button clicked successfully');
    }

    async clickLoginButton(): Promise<void> {
        console.log('🎯 Attempting to click Login button');
        const loginButton = this.page.locator('button:has-text("Login"), button:has-text("Sign In"), a:has-text("Sign In")').first();
        await expect(loginButton).toBeVisible({ timeout: 10000 });
        console.log('✅ Login button found and visible');
        await loginButton.click();
        console.log('✅ Login button clicked successfully');
    }

    // Verification Methods with enhanced logging
    async verifyPageStructure(): Promise<void> {
        console.log('🔍 Verifying page structure...');
        await expect(this.page).toHaveTitle(/./);
        await expect(this.page.locator('body')).toBeVisible();
        console.log('✅ Page structure verified');
    }

    async verifyTryButtonVisible(): Promise<void> {
        console.log('🔍 Checking "Try Calm for Free" button visibility...');
        await expect(this.tryButtonSelector).toBeVisible({ timeout: 10000 });
        console.log('✅ "Try Calm for Free" button is visible');
    }

    async verifySignInButtonVisible(): Promise<void> {
        console.log('🔍 Checking Sign In button visibility...');
        const signInButton = this.page.locator('button:has-text("Sign In"), button:has-text("Login"), a:has-text("Sign In")').first();
        await expect(signInButton).toBeVisible({ timeout: 10000 });
        console.log('✅ Sign In button is visible');
    }

    async verifyLinks(maxLinks: number = 10): Promise<void> {
        console.log(\`🔗 Starting link verification process (max \${maxLinks} links)...\`);
        const links = await this.linksSelector.all();
        console.log(\`📊 Found \${links.length} total links on page\`);
        
        let verifiedCount = 0;
        for (let i = 0; i < Math.min(links.length, maxLinks); i++) {
            const link = links[i];
            const href = await link.getAttribute('href');
            const isVisible = await link.isVisible();
            
            if (isVisible && href) {
                if (href.startsWith('mailto:') || href.startsWith('tel:')) {
                    console.log(\`⏭️ Skipping \${href.startsWith('mailto:') ? 'email' : 'phone'} link: \${href}\`);
                } else {
                    console.log(\`🔗 Verifying link \${i + 1}: \${href}\`);
                    expect(href).toBeTruthy();
                    expect(href).toMatch(/^https?:\\/\\//);
                    verifiedCount++;
                    console.log(\`✅ Link \${i + 1} verified successfully\`);
                }
            } else {
                console.log(\`⚠️ Link \${i + 1} is not visible or has no href\`);
            }
        }
        
        console.log(\`📈 Link verification completed: \${verifiedCount}/\${Math.min(links.length, maxLinks)} links verified\`);
    }

    async verifyImages(maxImages: number = 10): Promise<void> {
        console.log(\`🖼️ Starting image verification process (max \${maxImages} images)...\`);
        const images = await this.imagesSelector.all();
        console.log(\`📊 Found \${images.length} total images on page\`);
        
        let verifiedCount = 0;
        let brokenCount = 0;
        
        for (let i = 0; i < Math.min(images.length, maxImages); i++) {
            const img = images[i];
            const isVisible = await img.isVisible();
            
            if (isVisible) {
                const src = await img.getAttribute('src');
                if (src) {
                    console.log(\`🖼️ Verifying image \${i + 1}: \${src}\`);
                    expect(src).toBeTruthy();
                    
                    try {
                        const naturalWidth = await img.evaluate(img => img.naturalWidth);
                        expect(naturalWidth).toBeGreaterThan(0);
                        console.log(\`✅ Image \${i + 1} loaded successfully (width: \${naturalWidth}px)\`);
                        verifiedCount++;
                    } catch (error) {
                        console.log(\`❌ Image \${i + 1} failed to load: \${error.message}\`);
                        brokenCount++;
                    }
                } else {
                    console.log(\`⚠️ Image \${i + 1} has no src attribute\`);
                    brokenCount++;
                }
            } else {
                console.log(\`⚠️ Image \${i + 1} is not visible\`);
            }
        }
        
        console.log(\`📈 Image verification completed: \${verifiedCount} verified, \${brokenCount} broken\`);
    }

    async verifyPageHealth(): Promise<void> {
        console.log('🏥 Starting comprehensive page health check...');
        await this.verifyPageStructure();
        
        const pageTitle = await this.page.title();
        expect(pageTitle.length).toBeGreaterThan(0);
        console.log(\`📄 Page title: "\${pageTitle}"\`);
        
        const hasHeader = await this.headerSelector.isVisible().catch(() => false);
        const hasContent = await this.page.locator('main, .main, .content').isVisible().catch(() => false);
        const hasFooter = await this.page.locator('footer, .footer').isVisible().catch(() => false);
        
        console.log(\`🏗️ Page structure analysis:\`);
        console.log(\`   📍 Header: \${hasHeader ? '✅ Present' : '❌ Missing'}\`);
        console.log(\`   📄 Content: \${hasContent ? '✅ Present' : '❌ Missing'}\`);
        console.log(\`   📍 Footer: \${hasFooter ? '✅ Present' : '❌ Missing'}\`);
        
        // Check for common page elements
        const hasNavigation = await this.page.locator('nav, .nav, navigation').isVisible().catch(() => false);
        const hasForms = await this.page.locator('form').isVisible().catch(() => false);
        
        console.log(\`🔧 Interactive elements:\`);
        console.log(\`   🧭 Navigation: \${hasNavigation ? '✅ Present' : '❌ Missing'}\`);
        console.log(\`   📝 Forms: \${hasForms ? '✅ Present' : '❌ Missing'}\`);
        
        console.log('✅ Page health check completed');
    }
}
`;
    
    fs.writeFileSync(path.join(pageObjectsDir, "LandingPage.ts"), landingPageContent);
    console.log("✅ Created LandingPage page object");
}

function updatePageObjectsIndex() {
    const indexFile = path.join(repoRoot, "page-objects", "index.ts");
    let content = "// Page Objects Index\n// Auto-generated by AI Agent\n\n";
    
    content += "export * from './BasePage';\n";
    content += "export * from './LandingPage';\n";
    
    fs.writeFileSync(indexFile, content);
    console.log("✅ Updated page-objects index.ts");
}

// Main execution
if (import.meta.url === `file://${process.argv[1]}`) {
    console.log("🔧 Auto-creating missing project structure...");
    
    const poCreated = createPageObjectFolder();
    const utilsCreated = createUtilsFolder();
    
    if (poCreated || utilsCreated) {
        createLandingPagePO();
        updatePageObjectsIndex();
        console.log("✅ Project structure setup complete");
    } else {
        console.log("ℹ️ Project structure already exists");
    }
}

export { createPageObjectFolder, createUtilsFolder, createLandingPagePO, updatePageObjectsIndex };
