// Test Helpers
// Auto-generated by AI Agent

import { Page, expect } from '@playwright/test';

export class TestHelpers {
    static async verifyLinks(page: Page, maxLinks: number = 10): Promise<void> {
        const links = await page.locator('a[href]').all();
        console.log(`Found ${links.length} links to verify`);
        
        for (let i = 0; i < Math.min(links.length, maxLinks); i++) {
            const link = links[i];
            const href = await link.getAttribute('href');
            const isVisible = await link.isVisible();
            
            if (isVisible && href && !href.startsWith('mailto:') && !href.startsWith('tel:')) {
                console.log(`Verifying link: ${href}`);
                expect(href).toBeTruthy();
                expect(href).toMatch(/^https?:\/\//);
            }
        }
    }

    static async verifyImages(page: Page, maxImages: number = 10): Promise<void> {
        const images = await page.locator('img').all();
        
        for (const img of images.slice(0, maxImages)) {
            const isVisible = await img.isVisible();
            if (isVisible) {
                const src = await img.getAttribute('src');
                if (src) {
                    expect(src).toBeTruthy();
                    const naturalWidth = await img.evaluate(img => img.naturalWidth);
                    expect(naturalWidth).toBeGreaterThan(0);
                }
            }
        }
    }

    static async verifyPageHealth(page: Page): Promise<void> {
        await expect(page.locator('body')).toBeVisible();
        
        const pageTitle = await page.title();
        expect(pageTitle.length).toBeGreaterThan(0);
        console.log(`Page title: ${pageTitle}`);
        
        const hasHeader = await page.locator('header, .header, nav').isVisible().catch(() => false);
        const hasContent = await page.locator('main, .main, .content').isVisible().catch(() => false);
        
        console.log(`Header visible: ${hasHeader}, Content visible: ${hasContent}`);
    }
}
